# Generated by Django 4.1 on 2022-08-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.IntegerField()),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_Name', models.CharField(max_length=25)),
                ('room_Location', models.CharField(max_length=50)),
                ('number_Of_Beds', models.IntegerField()),
                ('numberOfStudents', models.IntegerField()),
                ('status', models.BooleanField()),
                ('room_Number', models.IntegerField()),
            ],
        ),
    ]
