# Generated by Django 4.1 on 2022-08-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_details',
            name='room_Number',
        ),
    ]
