# Generated by Django 4.1 on 2022-08-14 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelApp', '0002_remove_room_details_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_Name', models.CharField(max_length=25)),
                ('dob', models.DateTimeField(default=datetime.datetime.now)),
                ('gender', models.BooleanField()),
                ('status', models.BooleanField()),
                ('admission_Date', models.DateTimeField()),
                ('phonenumber', models.CharField(max_length=10)),
                ('studentAdmissionNumber', models.CharField(max_length=10)),
                ('id_number', models.CharField(max_length=15)),
                ('parent_Name', models.CharField(max_length=20)),
                ('parent_Contact', models.CharField(max_length=10)),
            ],
        ),
    ]
