# Generated by Django 4.1 on 2022-08-14 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelApp', '0003_student_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=15)),
                ('phonenumber', models.CharField(max_length=15)),
                ('admission_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
