# Generated by Django 4.1 on 2022-08-14 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostelApp', '0004_guardian_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('course', models.CharField(max_length=20)),
                ('signature', models.ImageField(upload_to='')),
                ('dateOfPayment', models.DateTimeField(default=datetime.datetime.now)),
                ('stud_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student_Registration_Receipt', to='hostelApp.receipt')),
                ('studentAdmissionNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudAdmissionNumber_Receipt', to='hostelApp.receipt')),
            ],
        ),
    ]
