# Generated by Django 4.1 on 2022-08-14 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelApp', '0005_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('admissionNumber', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('completion_date', models.DateTimeField(default=datetime.datetime.now)),
                ('phonenumber', models.CharField(max_length=10)),
                ('admission_Date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('studentId', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=20)),
                ('notification_Origin', models.CharField(max_length=15)),
                ('notification_Destination', models.CharField(max_length=15)),
                ('dateOfnotification', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
